#create a generator function with a similar mechanism as the generator expression you defined in the previous exercise

#Create a list of strings
lannister = ['cersei', 'jaime', 'tywin', 'tyrion', 'joffrey']

## Define generator function get_lengths
def get_lengths(input_list):
    """Generate function that yields the length of the strings in input list."""
    
    #yields the length of the strings
    for person in input_list:
        yield len(person)
     
       
#Print the values generated by get_lengths()
for values in get_lengths(lannister):
    print(values)